### ISSUE TITLE
values imported as factors

### ISSUE THREAD

**Issue by beatonan** [rywhale/rforecastca#1]
![image](https://user-images.githubusercontent.com/36272704/47387854-8ce98c80-d6de-11e8-8e5d-74051a1c1e61.png)

values that should be numeric are being imported as factors...ex Temperature and Wind_Speed

**Comment by rywhale** [comment]
Fixed this in the latest commit. 

https://github.com/rywhale/rforecastca/commit/7194af54a456bf5017ac9014e6de37a74bb7a77a

Update the package and you should be good.
